services:
  - type: web
    name: neuro-grade
    runtime: docker 
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: |
      php artisan config:clear
      php artisan cache:clear
      php artisan view:clear
      php artisan route:clear
      vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0phueruibrs73fsdo9g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neurograde_db
      - key: DB_USERNAME
        value: neurograde_db_user
      - key: DB_PASSWORD
        value: xo63rd6FnBqihnjbHQPK4SV0l6IIKHAF
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_LEVEL
        value: debug

  - type: worker
    name: neuro-grade-grading-worker
    runtime: docker 
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan queue:listen --queue=grading --tries=1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0phueruibrs73fsdo9g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neurograde_db
      - key: DB_USERNAME
        value: neurograde_db_user
      - key: DB_PASSWORD
        value: xo63rd6FnBqihnjbHQPK4SV0l6IIKHAF
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_LEVEL
        value: debug

databases:
  - name: neurograde-db
    databaseName: neurograde_db
    user: neurograde_db_user
    plan: free 