services:
  - type: web
    name: neuro-grade
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0phueruibrs73fsdo9g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neurograde_db
      - key: DB_USERNAME
        value: neurograde_db_user
      - key: DB_PASSWORD
        value: xo63rd6FnBqihnjbHQPK4SV0l6IIKHAF
      - key: QUEUE_CONNECTION
        value: database

  - type: worker
    name: neuro-grade-worker
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan queue:work --tries=3 --timeout=90
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0phueruibrs73fsdo9g-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neurograde_db
      - key: DB_USERNAME
        value: neurograde_db_user
      - key: DB_PASSWORD
        value: xo63rd6FnBqihnjbHQPK4SV0l6IIKHAF
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: neurograde-db
    databaseName: neurograde_db
    user: neurograde_db_user
    plan: free 